2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_setup.py:_flush():76] Configure stats pid to 21496
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_setup.py:_flush():76] Loading settings from C:\Users\fenel\.config\wandb\settings
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_setup.py:_flush():76] Loading settings from C:\Users\fenel\Documents\dcase2024_task1_baseline\wandb\settings
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'run_training_devices.py', 'program_abspath': 'C:\\Users\\fenel\\Documents\\dcase2024_task1_baseline\\run_training_devices.py', 'program': 'C:\\Users\\fenel\\Documents\\dcase2024_task1_baseline\\run_training_devices.py'}
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_init.py:_log_setup():524] Logging user logs to .\wandb\run-20250325_162535-wo0up4s1\logs\debug.log
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_init.py:_log_setup():525] Logging internal logs to .\wandb\run-20250325_162535-wo0up4s1\logs\debug-internal.log
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_init.py:init():607] calling init triggers
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {'project_name': 'DCASE24_Task1', 'experiment_name': 'Baseline', 'num_workers': 0, 'precision': '32', 'evaluate': False, 'ckpt_id': None, 'orig_sample_rate': 44100, 'subset': 5, 'n_classes': 10, 'in_channels': 1, 'base_channels': 32, 'channels_multiplier': 1.8, 'expansion_rate': 2.1, 'n_epochs': 150, 'batch_size': 256, 'mixstyle_p': 0.4, 'mixstyle_alpha': 0.3, 'weight_decay': 0.0001, 'roll_sec': 0.1, 'lr': 0.005, 'warmup_steps': 2000, 'sample_rate': 32000, 'window_length': 3072, 'hop_length': 500, 'n_fft': 4096, 'n_mels': 256, 'freqm': 48, 'timem': 0, 'f_min': 0, 'f_max': None}
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_init.py:init():657] starting backend
2025-03-25 16:25:35,359 INFO    MainThread:21496 [wandb_init.py:init():661] setting up manager
2025-03-25 16:25:35,370 INFO    MainThread:21496 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2025-03-25 16:25:35,378 INFO    MainThread:21496 [wandb_init.py:init():669] backend started and connected
2025-03-25 16:25:35,385 INFO    MainThread:21496 [wandb_init.py:init():764] updated telemetry
2025-03-25 16:25:35,676 INFO    MainThread:21496 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
2025-03-25 16:25:36,819 INFO    MainThread:21496 [wandb_run.py:_on_init():2479] communicating current version
2025-03-25 16:25:36,911 INFO    MainThread:21496 [wandb_run.py:_on_init():2488] got version response upgrade_message: "wandb version 0.19.8 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-03-25 16:25:36,911 INFO    MainThread:21496 [wandb_init.py:init():848] starting run threads in backend
2025-03-25 16:25:40,945 WARNING MainThread:21496 [wandb_init.py:init():1229] interrupted
Traceback (most recent call last):
  File "C:\Users\fenel\anaconda3\envs\d24_t1\lib\site-packages\wandb\sdk\wandb_init.py", line 1225, in init
    return wi.init()
  File "C:\Users\fenel\anaconda3\envs\d24_t1\lib\site-packages\wandb\sdk\wandb_init.py", line 861, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "C:\Users\fenel\anaconda3\envs\d24_t1\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "C:\Users\fenel\anaconda3\envs\d24_t1\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "C:\Users\fenel\anaconda3\envs\d24_t1\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "C:\Users\fenel\anaconda3\envs\d24_t1\lib\threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\fenel\anaconda3\envs\d24_t1\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2025-03-25 16:25:51,212 WARNING MsgRouterThr:21496 [router.py:message_loop():77] message_loop has been closed
